---
Name: Silverstripe SEO AI Configuration
---

Page:
  extensions:
    - PlasticStudio\SEOAI\Extensions\SeoAIExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - PlasticStudio\SEOAI\Extensions\SeoAISiteConfigExtension

Silverstripe\CMS\Controllers\CMSPageEditController:
  extensions:
    - PlasticStudio\SEOAI\Extensions\SeoAICMSPageEditControllerExtension

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - "client/css/cms.css"