---
Name: Silverstripe SEO AI Configuration
---

Page:
  extensions:
    - PlasticStudio\SEOAI\Extensions\SeoAIExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - PlasticStudio\SEOAI\Extensions\SeoAISiteConfigExtension